In [1]:
import pandas as pd

In [3]:
zipCodes = pd.read_csv("bayarea_zipcodes.csv")
zipCodes

,PO_NAME,the_geom,ZIP,STATE,Area__,Length__
0,NAPA,MULTIPOLYGON (((-122.10329200180091 38.5132829...,94558,CA,1.231326e+10,995176.225313
1,FAIRFIELD,MULTIPOLYGON (((-121.947475002335 38.301511000...,94533,CA,9.917861e+08,200772.556587
2,DIXON,MULTIPOLYGON (((-121.65335500334429 38.3133870...,95620,CA,7.236950e+09,441860.201400
3,SONOMA,MULTIPOLYGON (((-122.406843003057 38.155681999...,95476,CA,3.001414e+09,311318.546326
4,NAPA,MULTIPOLYGON (((-122.29368500225117 38.1552379...,94559,CA,1.194302e+09,359104.646602
...,...,...,...,...,...,...
182,LOS ALTOS,MULTIPOLYGON (((-122.09598200263689 37.3860539...,94022,CA,4.211365e+08,137369.776481
183,SUNNYVALE,MULTIPOLYGON (((-121.98688800346149 37.3886580...,94085,CA,9.054792e+07,47415.860456
184,SUNNYVALE,MULTIPOLYGON (((-122.05999500035823 37.3752980...,94086,CA,1.289431e+08,65560.361543
185,LOS ALTOS,MULTIPOLYGON (((-122.09598200263689 37.3860539...,94024,CA,2.966973e+08,136286.642980
186,SUNNYVALE,MULTIPOLYGON (((-122.06240400062882 37.3592939...,94087,CA,1.843369e+08,74339.948036

In [10]:
companyLocation = zipCodes.loc[(zipCodes['PO_NAME']=="MOUNTAIN VIEW")[0]

,PO_NAME,the_geom,ZIP,STATE,Area__,Length__
175,MOUNTAIN VIEW,MULTIPOLYGON (((-122.04438000129052 37.3942409...,94043,CA,2.364207e+08,99619.628143
178,MOUNTAIN VIEW,MULTIPOLYGON (((-122.03533900299037 37.4007049...,94035,CA,8.183875e+07,54976.900478
181,MOUNTAIN VIEW,MULTIPOLYGON (((-122.05999500035823 37.3752980...,94040,CA,9.875832e+07,79856.197832